### PR TITLE
fix(vocabularies): mark some resource-types unselectable

### PR DESCRIPTION
**Pull request by mirekys**
This will make some resource type vocab items unsellectable in form input (those having `submission` prop set to `false` )

### CODE REVIEW

**Review by Ducica — APPROVED** [review]

**Comment by Ducica** [comment]
When something is selected and you press x (clear), the selection is cleared, but it opens the modal again.
image

image

**Comment by Ducica** [comment]
Pretty funky issue. When you open the modal and type in something into the search bar (but it impacts only some items), for example you type in mat (for materials), you are unable to click to expand or to choose "conference materials"
image

If you however close the modal, open it again and type in conf, you can choose this item without issues. Similar issue can be seen for a few items, also Theses (etds), but only if you type etds!

**Comment by Ducica** [comment]
Should we make it possible to pass a placeholder to the Select field?

**Comment by mirekys** [comment]
> Pretty funky issue. When you open the modal and type in something into the search bar (but it impacts only some items), for example you type in mat (for materials), you are unable to click to expand or to choose "conference materials"
> If you however close the modal, open it again and type in conf, you can choose this item without issues. Similar issue can be seen for a few items, also Theses (etds), but only if you type etds!

This looks like a combination of factors like that Conference materials itself is non-selectable (submission:false) & all of its children don't match the filter. In that case it shouldn't be displayed at all to prevent confusion

**Comment by mirekys** [comment]
> Should we make it possible to pass a placeholder to the Select field?

Yes it makes perfect sense to me to have a placeholder there. I would do it in a separate PR tho :)

**Comment by mirekys** [comment]
> > Pretty funky issue. When you open the modal and type in something into the search bar (but it impacts only some items), for example you type in mat (for materials), you are unable to click to expand or to choose "conference materials"
> > If you however close the modal, open it again and type in conf, you can choose this item without issues. Similar issue can be seen for a few items, also Theses (etds), but only if you type etds!
> 
> This looks like a combination of factors like that Conference materials itself is non-selectable (submission:false) & all of its children don't match the filter. In that case it shouldn't be displayed at all to prevent confusion

Addressed in: https://github.com/oarepo/oarepo-vocabularies/pull/176/commits/3ede59e7cf4fe9f138fd962511f74cbc3e56e175

**Review by Ducica — APPROVED** [review]

**Pull request merged**
